name: Backend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest .

      - name: Push backend image
        run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy backend to AKS
        run: |
          kubectl set image deployment/backend-deployment backend=${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest
          kubectl rollout status deployment/backend-deployment
