name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build frontend Docker image
        run: |
          cd frontend
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest .

      - name: Push frontend image
        run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy frontend to AKS
        run: |
          kubectl set image deployment/frontend-deployment frontend=${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
          kubectl rollout status deployment/frontend-deployment
